# fly.toml app configuration file generated for arabic-tags on 2024-12-12T11:17:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arabic-tags'
primary_region = 'dfw'

[build]

[env]
  POSTGRES_DB = "arabic_tags"
  POSTGRES_USER = "postgres"
  # The host and password will be automatically set by Fly when you attach the database

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
